services:
  connection.factory.amqp:
    class: Vain\Amqp\Connection\Factory\AmqpConnectionFactory
    arguments: ['amqp']
    tags:
      - {name: connection.factory}
  queue.factory.amqp:
    class: Vain\Amqp\Queue\Factory\AmqpQueueFactory
    arguments: ['amqp']
    tags:
      - {name: queue.factory}